<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>TextBox</description>
   <name>SearchBox</name>
   <tag></tag>
   <elementGuidId>e79f8f93-b657-4683-8f16-6a75d134db06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@role='combobox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@role='combobox']</value>
   </webElementProperties>
</WebElementEntity>
